-- ============================================================
-- Generated by scripts/generate-seed-sql.js from docs/migration/r25-extracted.json
-- DO NOT hand-edit — re-run the generator instead, so the seed
-- always matches the frozen M-02 extraction manifest.
--
-- Known open item applied here: PLAYERS_DATA legacy_id 18 is
-- seeded with its live index.html display name ("Xuân Sử") —
-- see r25-data-reconciliation-plan.md §2 for the unresolved
-- name/asset-filename mismatch that must be confirmed with the
-- product owner before Release Candidate.
--
-- logo_path / avatar_path are left NULL here on purpose: they must
-- hold a real Supabase Storage object key, which does not exist
-- until M09 runs the actual upload against docs/migration/
-- r25-asset-manifest.json. Seeding a raw legacy relative path into
-- these columns would be an invalid/dangling reference.
-- ============================================================

-- Teams
insert into public.teams (id, name, full_name, icon, color, captain_name, stats, ovr, logo_path) values ('p', 'TEAM P', 'PHOENIX', '🦅', '#1A5BB5', 'Anh Trương', '{"attack":92,"defense":88,"speed":90,"power":85}'::jsonb, 89, null);
insert into public.teams (id, name, full_name, icon, color, captain_name, stats, ovr, logo_path) values ('t', 'TEAM T', 'TIGER', '🐯', '#D32F2F', 'Minh Thế', '{"attack":88,"defense":85,"speed":80,"power":90}'::jsonb, 86, null);
insert into public.teams (id, name, full_name, icon, color, captain_name, stats, ovr, logo_path) values ('x', 'TEAM X', 'XIPHIAS', '🐟', '#F5A623', 'Đình Huy', '{"attack":85,"defense":90,"speed":95,"power":82}'::jsonb, 88, null);

-- Players
insert into public.players (legacy_id, name, team_id, position, avatar_path) values (1, 'Anh Trương', 'p', 'FW', null);
insert into public.players (legacy_id, name, team_id, position, avatar_path) values (2, 'Phan Hiền', 'p', 'MF', null);
insert into public.players (legacy_id, name, team_id, position, avatar_path) values (3, 'Thanh Long', 'p', 'DF', null);
insert into public.players (legacy_id, name, team_id, position, avatar_path) values (4, 'Thanh Trúc', 'p', 'GK', null);
insert into public.players (legacy_id, name, team_id, position, avatar_path) values (5, 'Mậu Quốc', 'p', 'DF', null);
insert into public.players (legacy_id, name, team_id, position, avatar_path) values (6, 'Quang Minh', 'p', 'FW', null);
insert into public.players (legacy_id, name, team_id, position, avatar_path) values (7, 'Khánh Hưng', 'p', 'MF', null);
insert into public.players (legacy_id, name, team_id, position, avatar_path) values (8, 'Mạnh Tuấn', 'p', 'DF', null);
insert into public.players (legacy_id, name, team_id, position, avatar_path) values (9, 'Minh Thế', 't', 'DF', null);
insert into public.players (legacy_id, name, team_id, position, avatar_path) values (10, 'Tường Khánh', 't', 'GK', null);
insert into public.players (legacy_id, name, team_id, position, avatar_path) values (11, 'Hoàng Nam', 't', 'MF', null);
insert into public.players (legacy_id, name, team_id, position, avatar_path) values (12, 'Đăng Quân', 't', 'FW', null);
insert into public.players (legacy_id, name, team_id, position, avatar_path) values (13, 'Thanh Tú', 't', 'FW', null);
insert into public.players (legacy_id, name, team_id, position, avatar_path) values (14, 'Chí Đại', 't', 'MF', null);
insert into public.players (legacy_id, name, team_id, position, avatar_path) values (15, 'Quang Toàn', 't', 'DF', null);
insert into public.players (legacy_id, name, team_id, position, avatar_path) values (16, 'Phát Tài', 't', 'DF', null);
insert into public.players (legacy_id, name, team_id, position, avatar_path) values (17, 'Đình Huy', 'x', 'GK', null);
insert into public.players (legacy_id, name, team_id, position, avatar_path) values (18, 'Xuân Sử', 'x', 'DF', null);
insert into public.players (legacy_id, name, team_id, position, avatar_path) values (19, 'Văn Lân', 'x', 'FW', null);
insert into public.players (legacy_id, name, team_id, position, avatar_path) values (20, 'Thiên Phú', 'x', 'DF', null);
insert into public.players (legacy_id, name, team_id, position, avatar_path) values (21, 'Bảo Anh', 'x', 'MF', null);
insert into public.players (legacy_id, name, team_id, position, avatar_path) values (22, 'Phương Toàn', 'x', 'MF', null);
insert into public.players (legacy_id, name, team_id, position, avatar_path) values (23, 'Minh Hiếu', 'x', 'FW', null);
insert into public.players (legacy_id, name, team_id, position, avatar_path) values (24, 'Thành Thái', 'x', 'MF', null);

-- Matches
insert into public.matches (legacy_id, home_team_id, away_team_id, match_date, start_time, end_time) values (1, 'p', 't', '2026-08-07', '17:00', '17:35');
insert into public.matches (legacy_id, home_team_id, away_team_id, match_date, start_time, end_time) values (2, 'p', 'x', '2026-08-07', '17:50', '18:25');
insert into public.matches (legacy_id, home_team_id, away_team_id, match_date, start_time, end_time) values (3, 'x', 't', '2026-08-07', '18:40', '19:15');

-- Tournament settings
update public.tournament_settings set slogan = 'Làm hết sức – Chơi hết mình', message = 'Giải bóng đá truyền thống do Công đoàn PTX Group Việt Nam tổ chức', event_date = '07/08/2026', location = '152 Hoàng Hoa Thám, Bảy Hiền, Hồ Chí Minh, Việt Nam' where id = true;

-- Hall of Fame
-- champion/runner_up/third_place resolved from legacy free-text
-- "TEAM X (FULLNAME)" labels against the teams seeded above.
-- golden_boot/mvp are player NAMES, not yet resolved to players.id
-- (legacy export has no player-id reference for these, only a
-- display name) — left NULL with the name recorded in a comment
-- for manual admin-panel assignment once M04/M11 exist.
insert into public.hall_of_fame (year, champion_team_id, runner_up_team_id, third_place_team_id) values (2025, 'p', null, null) on conflict (year) do update set champion_team_id = excluded.champion_team_id, runner_up_team_id = excluded.runner_up_team_id, third_place_team_id = excluded.third_place_team_id;
